universe       = vanilla
executable     = conv_probe.sh
output         = logs/convprobe_volta.$(ClusterId).out
error          = logs/convprobe_volta.$(ClusterId).err
log            = logs/convprobe_volta.$(ClusterId).log
request_gpus   = 1
request_cpus   = 2
request_memory = 8000
requirements   = TARGET.GPUs_GlobalMemoryMb >= 20000 && TARGET.GPUs_Capability >= 7.0 && TARGET.GPUs_Capability < 8.0
+MaxRuntime    = 1800
+JobBatchName  = "conv-probe-volta"
queue 1
