universe       = vanilla
executable     = strip_cell.sh
arguments      = $(seed) $(pair) $(repr) $(reveal) /afs/cern.ch/work/m/maborisy/ship-strip-test/$(repr)-$(reveal)/$(seed)/pair$(pair)
output         = logs/striptest_$(seed)_$(pair).$(ClusterId).$(ProcId).out
error          = logs/striptest_$(seed)_$(pair).$(ClusterId).$(ProcId).err
log            = logs/striptest.$(ClusterId).log
request_gpus   = 1
request_cpus   = 2
request_memory = 12000
requirements   = TARGET.GPUs_GlobalMemoryMb >= 20000 && TARGET.GPUs_Capability >= 8.0
+MaxRuntime    = 72000
+JobBatchName  = "ship-strip-test"
queue seed,pair,repr,reveal from (
  1244111331, 5, strip, none
)
