sparse_straw:
  # Station z-positions (mm)
  event_path: data/MC.npz
  n_stations: 4
  n_views_per_station: 4
  n_layers_per_view: 2
  n_straws_per_layer: 200 # Set to your actual number

  # Straw geometry
  straw_length: 600.0 # cm
  straw_pitch: 3.0 # cm (centre-to-centre in a layer)
  layer_x_offset: 1.0 # cm (Layer-2 vs Layer-1 x-offset)

  # View geometry
  layer_z_gap: 2.0 #1.732 # cm (between layers in a view)
  view_z_gap: 5.0 # cm (between consecutive views)

  # Physics parameters
  dt: 1.0e-1
  max_B: 0.8 #8e-6
  B_z0: 3098.0 # Center of magnetic field (cm)
  B_sigma: 300.0 # Sigma (width) of magnetic field (cm)

  station_z_bounds: [2600., 4000.] # for encoding/decoding
  view_angle_bounds: [-0.2, 0.2]

  straw_signal_rate: 5_000_000.0
  straw_noise_rate: 100_000.0
  straw_time_normalization: 150.0

  hnl_position_offset: [0.0, 0.0, 0.0]
  hnl_position_scale: [200.0, 200.0, 1000.0]

  hnl_momentum_offset: [0.0, 0.0, 0.0]
  hnl_momentum_scale: [0.5, 0.5, 20.0]
