detector: stereo
design: initial_stereo

regressor:
  induced-set-regressor:
    features: [ [ 64, 32 ], [ 64, 32 ]]
    induced: 8

optimizer:
  adamw:
    learning_rate:
      cosine_decay_schedule:
        init_value: 1.0e-3

    weight_decay: 1.0e-6

sampling:
  batch: 1024

training:
  batch: 32
  epochs: 2048
  samples: 65536

validation:
  batch: 128
  samples: 16384
