detector: straw

regressor:
  deep-set:
    features: [[64, 128], [128, 96]]
    p_dropout: 0.1

optimizer:
  adabelief:
    learning_rate: 1e-4

initial_design: data/design/default.json

batch: 32
epochs: 32
steps: 6000

validation_batches: 32

report: output/losses.png
