detector: stereo
design: initial_stereo

regressor:
  set-regressor:
    features: [ [ 64, 32 ], [ 64, 32 ], [ 64, 32 ] ]

optimizer:
  adamw:
    learning_rate:
      cosine_decay_schedule:
        init_value: 1.0e-3

    weight_decay: 1.0e-3

sampling:
  batch: 1024

training:
  batch: 32
  epochs: 32
  samples: 32768

validation:
  batch: 128
  samples: 16384

report: output/losses.png
