detector: straw

plot_per_epoch: 8

regressor: deep-set-24
discriminator: deep-set-24
generator: deep-set-vae-64

initial_design: data/design/default.json
trace: data/design/vae/

eps: 1.0e-2
likelihood_sigma: 1.0e-1

optimizer:
  adam:
    learning_rate: 1.0e-3
    b1: 0.99
    b2: 0.998

epochs: 32
steps: 1024
substeps: 1

batch: 8
validation_batches: 1024